# grappler CONFIGURATION !!! v1

# do you want grappler to be enabled?
grappler: true
grapplercooldown: 2


#Messages:

GladAlready: '&7Você já estã no gladiador'
BlockCommandGlad: '&7Sem comandos no gladiador'
Only-kit-users: '&cVocê só pode usar kit gladiador em pessoas com kit'
ender-pearl-block: '&4EnderPearl não é permitida em glad'
NPC-BLOCK: '&4Não é possivel desafiar NPCs'
NoWinner-Warn: '&bSe em 5 minutos não houver vencedores voltaram para o mesmo local'
Was-Challenge: '&aVocê foi desafiado para uma arena Glad por: '
You-Challenge: '&bVocê desafiou o jogador: '
Enemy-Disconnect: '&4Seu oponente desconectou'

